### ISSUE TITLE
Won't let me save a profile

### ISSUE THREAD

**Issue by iCreatZ** [DrExpresso/SupremeAIO#1]
Hey there,

I've downloaded the latest release from you, and love the design and all the options but now I tried making a profile but it won't let me save it. Any chance you could help me?

**Comment by DrExpresso** [comment]
I think you need to right click on SupremeAIO icon and run as administrator otherwise it doesn't have permission to write in program files

**Comment by iCreatZ** [comment]
Yup that was it, thanks man!
